config/routes.rb
Rails.application.routes.draw do
  root to: "pokemons#index"

  resources :pokemons, only: %i[show] do
    resources :pokeballs, only: %i[new create]
  end

  resources :trainers, only: %i[index show]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :trainer
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  has_one_attached :photo
  has_many :pokeballs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController
  before_action :set_pokemon, only: %i[new create]

  def new
    @pokeball = Pokeball.new
  end

  def create
    @pokeball = Pokeball.new(pokeball_params)
    @pokeball.pokemon = @pokemon
    if rand < 0.5
      flash[:alert] = "Oh no, the pokemon escaped. Try again!"
      render "pokemons/show", status: :unprocessable_entity
      return
    end

    if @pokeball.save
      redirect_to @pokeball.trainer
    else
      render "pokemons/show", status: :unprocessable_entity
    end
  end

  private

  def pokeball_params
    params.require(:pokeball).permit(:location, :caught_on, :pokemon_id, :trainer_id)
  end

  def set_pokemon
    @pokemon = Pokemon.find(params[:pokemon_id])
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @pokeball = Pokeball.new
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPokemon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pokeballs/new.html.erb
<h1>Pokeballs#new</h1>
<p>Find me in app/views/pokeballs/new.html.erb</p>

app/views/pokemons/index.html.erb
<div class="container">

  <h1 class="text-white mt-3">Pokedex</h1>

  <h5><%= link_to "Trainers", trainers_path, class: "underlined golden" %></h5>
  <h5><%= link_to "Random Pokémon", trainers_path, class: "underlined golden" %></h5>

  <div class="row mt-3">
    <% @pokemons.each do |pokemon| %>
      <div class="col-md-3 mb-3">
        <div class="card bg-light-blue">
          <%= image_tag url_for(pokemon.photo), alt: "Pokemon picture", class: "pokemon-pic-rounded" %>
          <h4 class="text-white text-center"><%= pokemon.name %></h4>
          <h5 class="golden text-center"><%= pokemon.element_type %></h5>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemons/show.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>


<div class="container mt-3">
  <h4><%= link_to "< Pokedex", root_path, class: "btn btn-link" %></h4>

  <div class="row">
    <div class="col-md-6">
      <div class="card card-pokemon-size bg-light-blue">
        <%= image_tag url_for(@pokemon.photo), alt: "Pokemon picture", class: "pokemon-pic-rounded" %>
        <h4 class="text-white text-center"><%= @pokemon.name %></h4>
        <h5 class="golden text-center"><%= @pokemon.element_type %></h5>
      </div>
    </div>
    <div class="col-md-6">
      <h5 class="text-white">Do you dare to catch this pokemon?</h5>
      <%= simple_form_for [@pokemon, @pokeball] do |f| %>
        <%= f.association :trainer, collection: Trainer.all, prompt: "Who's trying their luck?" %>
        <%= f.dropdown :location, label: "Where are you?" %>
        <%= f.input :caught_on, as: :string, input_html: { type: 'date' } %>
        <%= f.button :submit, "Throw the pokeball!" class: "btn btn-gold" %>
      <% end %>
    </div>
  </div>
</div>

app/views/trainers/index.html.erb
<div class="container">
  <h4><%= link_to "< Pokedex", root_path, class: "btn btn-link" %></h4>

  <h2 class="text-white">Let's Catch Some Pokemon</h2>

  <div class="row">
    <% @trainers.each do |trainer| %>
      <div class="col-md-4 d-flex justify-content-center">
        <div class="card card-trainers-size bg-light-blue d-flex flex-column align-items-center p-3">
          <div class="trainer-image-container">
            <%= image_tag url_for(trainer.photo), alt: "Trainer picture", class: "trainer-image" %>
          </div>
          <h5 class="text-center golden mt-3"><%= trainer.name %></h5>
          <h5 class="text-center text-white"><%= trainer.age %></h5>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/trainers/show.html.erb
<div class="container mt-3">
  <h4><%= link_to "< Pokedex", root_path, class: "btn btn-link" %></h4>

  <div class="row">
    <div class="col-md-6">
      <div class="card card-trainer-size bg-light-blue">
        <%= image_tag url_for(@trainer.photo), alt: "Trainer picture", class: "trainer-pic-rounded" %>
        <h4 class="text-white text-center"><%= @trainer.name %></h4>
        <h5 class="golden text-center"><%= @trainer.age %></h5>
      </div>
    </div>
    <div class="col-md-6">
      <h3>Their pokemon</h3>
      <div class="row">
        <% @trainer.pokeballs.each do |pokeball| %>
          <div class="col-md-6">
            <div class="card bg-light-blue mb-3">
              <%= image_tag url_for(pokeball.pokemon.photo), alt: "Pokemon photo", class: "pokemon-pic-rounded" %>
              <h4 class="text-center text-white"><%= pokeball.pokemon.name %></h4>
              <h4 class="text-center golden"><%= pokeball.pokemon.element_type %></h4>
              <h5 class="p-2 text-center"><%= "Caught on #{pokeball.caught_on} at #{pokeball.location}" %></h5>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>